services:

  db:
    image: postgres:16
    container_name: journal-db
    environment:
      POSTGRES_DB: journal_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5443:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: journal-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/journal_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: journal-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pg_data:
