spring.datasource.url=jdbc:postgresql://localhost:5443/journal_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=dev-secret-key-min-32-characters-long!!
jwt.expiration-ms=86400000
